<?php
return array (
  19 => 
  array (
    'id' => '19',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-01s',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 青岛傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=19',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1445939744',
    'updatetime' => '1449650622',
    'hitsid' => 'c-3-19',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  18 => 
  array (
    'id' => '18',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-kulou',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 青岛傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=18',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1445939724',
    'updatetime' => '1445939742',
    'hitsid' => 'c-3-18',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  20 => 
  array (
    'id' => '20',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-yemab',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 青岛傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=20',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449651168',
    'updatetime' => '1449651186',
    'hitsid' => 'c-3-20',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  31 => 
  array (
    'id' => '31',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-MM',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=31',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727426',
    'updatetime' => '1449727450',
    'hitsid' => 'c-3-31',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  32 => 
  array (
    'id' => '32',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-daoshi',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=32',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449730217',
    'updatetime' => '1449730250',
    'hitsid' => 'c-3-32',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  33 => 
  array (
    'id' => '33',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-gegewu',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 青岛傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=33',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449742721',
    'updatetime' => '1449742746',
    'hitsid' => 'c-3-33',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  34 => 
  array (
    'id' => '34',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-fashim',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 青岛傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=34',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449742750',
    'updatetime' => '1449742777',
    'hitsid' => 'c-3-34',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  35 => 
  array (
    'id' => '35',
    'catid' => '18',
    'typeid' => '0',
    'title' => 'allsure-daoshi',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 青岛傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=18&id=35',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449742794',
    'updatetime' => '1449742819',
    'hitsid' => 'c-3-35',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>