<?php
return array (
  11 => 
  array (
    'id' => '11',
    'catid' => '15',
    'typeid' => '0',
    'title' => '侠客',
    'style' => '',
    'thumb' => '',
    'keywords' => '影片测试',
    'description' => '影片测试',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=15&id=11',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1445831131',
    'updatetime' => '1449649414',
    'hitsid' => 'c-3-11',
    'views' => '2',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  21 => 
  array (
    'id' => '21',
    'catid' => '15',
    'typeid' => '0',
    'title' => '江湖女弟子',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=15&id=21',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449651269',
    'updatetime' => '1457341512',
    'hitsid' => 'c-3-21',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
);
?>