<?php
return array (
  16 => 
  array (
    'id' => '16',
    'catid' => '16',
    'typeid' => '0',
    'title' => '刘烨 诺一 nuoyi',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => 'http:  player youku com player php sid XMTM3OTYwNDkyNA== v swf',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=16&id=16',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1445937870',
    'updatetime' => '1449651365',
    'hitsid' => 'c-3-16',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  25 => 
  array (
    'id' => '25',
    'catid' => '16',
    'typeid' => '0',
    'title' => '爸爸去哪儿',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=16&id=25',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449714243',
    'updatetime' => '1449714268',
    'hitsid' => 'c-3-25',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>