<?php
return array (
  29 => 
  array (
    'id' => '29',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'allsure-nvdizi',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=29',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727284',
    'updatetime' => '1449727324',
    'hitsid' => 'c-3-29',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  30 => 
  array (
    'id' => '30',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'allsure-mofash',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=30',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727373',
    'updatetime' => '1449727412',
    'hitsid' => 'c-3-30',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>