<?php
return array (
  12 => 
  array (
    'id' => '12',
    'catid' => '17',
    'typeid' => '0',
    'title' => '宫爆老奶奶  老奶奶',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '作品的简介填在这里',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=12',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'admin',
    'inputtime' => '1445836593',
    'updatetime' => '1445933907',
    'hitsid' => 'c-3-12',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  23 => 
  array (
    'id' => '23',
    'catid' => '17',
    'typeid' => '0',
    'title' => '游戏icon',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=23',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449652069',
    'updatetime' => '1449727205',
    'hitsid' => 'c-3-23',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  28 => 
  array (
    'id' => '28',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'app_icon',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=28',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727215',
    'updatetime' => '1457341597',
    'hitsid' => 'c-3-28',
    'views' => '1',
    'yesterdayviews' => '0',
    'dayviews' => '1',
    'weekviews' => '1',
    'monthviews' => '1',
  ),
  26 => 
  array (
    'id' => '26',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'allsure-野蛮',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=26',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449718275',
    'updatetime' => '1449718309',
    'hitsid' => 'c-3-26',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  27 => 
  array (
    'id' => '27',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'allsure-bigdos',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=27',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727144',
    'updatetime' => '1449727171',
    'hitsid' => 'c-3-27',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  29 => 
  array (
    'id' => '29',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'allsure-nvdizi',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=29',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727284',
    'updatetime' => '1449727324',
    'hitsid' => 'c-3-29',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
  30 => 
  array (
    'id' => '30',
    'catid' => '17',
    'typeid' => '0',
    'title' => 'allsure-mofash',
    'style' => '',
    'thumb' => '',
    'keywords' => '傲雪 青岛傲雪 傲雪数码',
    'description' => '',
    'posids' => '0',
    'url' => 'http://www.cgassist.com/index.php?m=content&c=index&a=show&catid=17&id=30',
    'listorder' => '0',
    'status' => '99',
    'sysadd' => '1',
    'islink' => '0',
    'username' => 'duanshuai',
    'inputtime' => '1449727373',
    'updatetime' => '1449727412',
    'hitsid' => 'c-3-30',
    'views' => '0',
    'yesterdayviews' => '0',
    'dayviews' => '0',
    'weekviews' => '0',
    'monthviews' => '0',
  ),
);
?>